.github/workflows/build.yaml

Allow preview builds of the language specification PDF on build in addition to adopted versions on main.

Allow language spec PDF to build on main or dev.

---

src/main/java/org/joshsim/lang/interpret/ValueResolver.java
src/test/java/org/joshsim/lang/interpret/ValueResolverTest.java

Added ValueResolver which can follow Josh language variable paths to get EngineValue within ANTLR interpreter.

Add value resolver.

---

src/main/java/org/joshsim/engine/entity/Agent.java
src/main/java/org/joshsim/engine/entity/AttributeContainer.java
src/main/java/org/joshsim/engine/entity/AttributeManaging.java
src/main/java/org/joshsim/engine/entity/Disturbance.java
src/main/java/org/joshsim/engine/entity/Entity.java
src/main/java/org/joshsim/engine/entity/EntityBuilder.java
src/main/java/org/joshsim/engine/entity/EventHandler.java
src/main/java/org/joshsim/engine/entity/EventHandlerGroup.java
src/main/java/org/joshsim/engine/entity/EventHandlerGroupBuilder.java
src/main/java/org/joshsim/engine/entity/EventKey.java
src/main/java/org/joshsim/engine/entity/ExternalResource.java
src/main/java/org/joshsim/engine/entity/Lockable.java
src/main/java/org/joshsim/engine/entity/MemberSpatialEntity.java
src/main/java/org/joshsim/engine/entity/Patch.java
src/main/java/org/joshsim/engine/entity/RootSpatialEntity.java
src/main/java/org/joshsim/engine/entity/Simulation.java
src/main/java/org/joshsim/engine/entity/SpatialEntity.java
src/main/java/org/joshsim/engine/func/EntityScope.java
src/main/java/org/joshsim/engine/geometry/GridBuilder.java
src/main/java/org/joshsim/lang/bridge/ShadowingEntity.java
src/test/java/org/joshsim/engine/entity/AgentTest.java
src/test/java/org/joshsim/engine/entity/EntityBuilderTest.java
src/test/java/org/joshsim/engine/entity/EventHandlerGroupBuilderTest.java
src/test/java/org/joshsim/engine/entity/EventHandlerGroupTest.java
src/test/java/org/joshsim/engine/entity/PatchTest.java
src/test/java/org/joshsim/lang/bridge/ShadowingEntityTest.java

Entity implementations:
- `Entity` (Simulation) do not have geometry
- `SpatialEntity` does have geometry but
- `MemberSpatialEntity` gets its geometry from a parent (includes `Agent` and `Disturbance`)
- `RootSpatialEntity` has its own geometry (includes only `Patch` for now)
`EntityBuilder` builds each one as appropriate.
Also, `EventHandler` and `EventHandlerGroup` are implemented, along with `EventHandlerGroupBuilder` (we assume we can build an `EventHandler` in one shot without a builder).

Entities and EventHandlers

---

src/main/java/org/joshsim/engine/value/type/RealizedDistribution.java
src/main/java/org/joshsim/lang/interpret/machine/SingleThreadEventHandlerMachine.java
src/test/java/org/joshsim/engine/value/type/RealizedDistributionTest.java

As part of #51, add implementation for random sampling.

Add random sampling.

---

src/main/java/org/joshsim/engine/value/converter/Units.java
src/main/java/org/joshsim/lang/interpret/JoshParserToMachineVisitor.java
src/test/java/org/joshsim/engine/value/converter/UnitsTest.java

Do not include units into units strings to avoid things like `m * counts`.

Add counts erasure

---

.replit
build.gradle
editor/index.html
editor/js/run.js
editor/js/wasm.worker.js
editor/style/style.css
editor/war/get_from_jar.sh
examples/simulations/web_geo.josh
src/main/java/org/joshsim/JoshSimCommander.java
src/main/java/org/joshsim/JoshSimFacadeUtil.java
src/main/java/org/joshsim/cloud/CloudApiDataLayer.java
src/main/java/org/joshsim/cloud/EnvCloudApiDataLayer.java
src/main/java/org/joshsim/cloud/JoshSimLeaderHandler.java
src/main/java/org/joshsim/cloud/JoshSimServer.java
src/main/java/org/joshsim/cloud/JoshSimWorkerHandler.java
src/main/java/org/joshsim/engine/geometry/HaversineUtil.java
src/main/java/org/joshsim/lang/bridge/GridFromSimFactory.java
src/main/java/org/joshsim/lang/bridge/GridInfoExtractor.java
src/main/java/org/joshsim/lang/io/MapToMemoryStringConverter.java
src/test/java/org/joshsim/cloud/EnvCloudApiDataLayerTest.java
src/test/java/org/joshsim/cloud/JoshSimLeaderHandlerTest.java
src/test/java/org/joshsim/cloud/JoshSimWorkerHandlerTest.java
src/test/java/org/joshsim/engine/geometry/HaversineUtilTest.java

Add local server and local server detection but not quite to the point of running simulations back on local.

Add local server

---

editor/js/engine.js
src/main/java/org/joshsim/cloud/ApiKeyUtil.java
src/main/java/org/joshsim/cloud/JoshSimLeaderHandler.java
src/main/java/org/joshsim/cloud/JoshSimWorkerHandler.java
src/test/java/org/joshsim/cloud/JoshSimLeaderHandlerTest.java
src/test/java/org/joshsim/cloud/JoshSimWorkerHandlerTest.java

Just realizing that we can probably simplify the process for self-deployment through this route.

Move from API key in header to form

---

editor/index.html
editor/js/data.js
editor/js/data.worker.js
editor/js/engine.js
editor/js/file.js
editor/js/main.js
editor/js/wasm.js
editor/style/style.css
src/main/java/org/joshsim/cloud/JoshSimLeaderHandler.java
src/main/java/org/joshsim/cloud/JoshSimWorkerHandler.java

Implementation of OPFS for holding external data files in the browser sent to the server or WASM thread.

Add OPFS support for external data added in editor.

---

editor/js/run.js
joshpy/joshpy/remote.py

Fast forward on main from #151.

Push prod endpoints to prod.

---

examples/tutorial/succession.josh

I will use this branch and assign myself and Sam as reviewer so I can comment on the file

Used bioclimatic limits internally

---

editor/index.html
editor/js/data.js
editor/js/engine.js
editor/js/parse.js
editor/js/run.js
editor/js/wasm.js
editor/js/wasm.worker.js
editor/js/wire.js
src/main/java/org/joshsim/command/ServerCommand.java
src/main/java/org/joshsim/lang/bridge/ShadowingEntity.java
src/main/java/org/joshsim/lang/bridge/SyntheticScope.java

* Fixes from running in browser.
* Bump cache busters.

Fast forward main

---

examples/tutorial/succession.josh
examples/tutorial/succession.md

Sorry @lucialayr - for real this time! Please let me know what you think. Note that I also bumped the density up to 100 organisms per patch from 10. I moved to 200 meter resolution though just to make sure it was still speedy for a demo. At 100 it's not too terribly slow but just thinking about the cadence of the live demo. However, LMK what a more realistic number might be. Thank you!

Responses to @lucialayr comments on #150.

---

src/main/antlr/org/joshsim/lang/antlr/JoshLang.g4
src/main/java/org/joshsim/lang/interpret/JoshParserToMachineVisitor.java
src/main/java/org/joshsim/lang/interpret/machine/SingleThreadEventHandlerMachine.java
src/main/java/org/joshsim/lang/interpret/mapping/LinearMapStrategy.java
src/main/java/org/joshsim/lang/interpret/mapping/MapBounds.java
src/main/java/org/joshsim/lang/interpret/mapping/MapStrategy.java
src/main/java/org/joshsim/lang/interpret/mapping/QuadraticMapStrategy.java
src/main/java/org/joshsim/lang/interpret/mapping/SigmoidMapStrategy.java
src/test/java/org/joshsim/lang/interpret/mapping/LinearMapStrategyTest.java
src/test/java/org/joshsim/lang/interpret/mapping/QuadraticMapStrategyTest.java
src/test/java/org/joshsim/lang/interpret/mapping/SigmoidMapStrategyTest.java

Release new map strategies into main.

---

landing/guides/grass_shrub_fire.html
landing/guides/hello.html
src/main/java/org/joshsim/lang/interpret/machine/SingleThreadEventHandlerMachine.java
src/main/java/org/joshsim/lang/interpret/mapping/MappingBuilder.java

Prod accidentally calling dev for worker distribution

Fix the URL used in prod

---

editor/js/engine.js

* Fix incorrect flip on serial patches.
* Bug fix in close non-empty stream
* Assistant checkpoint: Add reader cleanup and improve buffer handling
Assistant generated file changes:
- editor/js/engine.js: Add reader cleanup and improve buffer handling
---
User prompt:
Hello! In @editor/js/engine.js, can you ensure the reader used in RemoteEngineBackend is released? Also, is handling of the buffer when done correct?
Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: 9e6590b7-1a9f-4f37-9957-e77f532942ed
* Assistant checkpoint: Add reader cleanup in error handling
Assistant generated file changes:
- editor/js/engine.js: Add reader cleanup in catch block
---
User prompt:
Should a reader.releaseLock also be added in
Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: …

Deploy bug fix on close stream to main

---

src/main/java/org/joshsim/engine/value/converter/ConverterBuilder.java
src/main/java/org/joshsim/engine/value/converter/DirectConversion.java
src/main/java/org/joshsim/engine/value/converter/MapConverter.java
src/main/java/org/joshsim/lang/interpret/visitor/delegates/JoshStanzaVisitor.java
src/test/java/org/joshsim/lang/interpret/visitor/AliasConversionIntegrationTest.java

Fix a silent issue not allowing aliases to
be added bidirectionally. Closes https://github.com/SchmidtDSE/josh/issues/204.

Fix alias bidirectionality

---

.github/workflows/build.yaml
examples/guide/grass_shrub_fire.josh
examples/guide/grass_shrub_fire_cli.josh
examples/guide/hello.josh
examples/guide/hello_cli.josh
examples/guide/two_trees.josh
examples/guide/two_trees_cli.josh
examples/test.sh
landing/guides/grass_shrub_fire.html
landing/guides/hello.html
landing/guides/two_trees.html

Add guide examples to test and touch up.

---

editor/js/engine.js
editor/js/main.js
editor/js/parse.js
src/main/java/org/joshsim/cloud/JoshSimLeaderHandler.java
src/main/java/org/joshsim/cloud/JoshSimWorkerHandler.java

Fix the steps-level progress bar from remote due to fixed leader streaming.

Fix streaming for steps progress.

---

editor/index.html
editor/js/editor.js
editor/js/wasm.js
editor/js/wasm.worker.js

Revert "Isolate the staging environment."

---

cloud-img/Dockerfile.dev
cloud-img/Dockerfile.prod

Increase the number of concurrent workers allowed in Josh Cloud, both in prod and staging.

Increase Josh Cloud allowances.

---

src/main/java/org/joshsim/JoshSimFacadeUtil.java
src/main/java/org/joshsim/command/PreprocessCommand.java
src/main/java/org/joshsim/lang/interpret/FutureBridgeGetter.java
src/main/java/org/joshsim/precompute/JshcConfigGetter.java
src/test/java/org/joshsim/precompute/JshcConfigGetterTest.java

Use JshcConfigGetter instead of NoOpConfigGetter for production code but allow its use in tests.

Fix use of JshcConfigGetter.
